const api=[
    {
        pid:1,
        pname:"Cream Tshirl",
        src:"http://localhost:3000/img/slider/pic1.jpg",
        ptitle:"Big Brand Textile",
        pcolor:"Cream-Brown",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Cotton Mix",
        type:"Half Sleves",
    },
    {
        pid:2,
        pname:"Blue Tshirt",
        src:"http://localhost:3000/img/slider/pic2.jpg",
        ptitle:"Big Brand Textile",
        pcolor:"Dark Blue with Yellow Logo",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Cotton Mix",
        type:"Half Sleves",
    },
    {
        pid:3,
        pname:"Black Jacket",
        src:"http://localhost:3000/img/slider/pic3.jpg",
        ptitle:"Big Brand Textile",
        pcolor:"Black Combination",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Fiberic Wool",
        type:"Full Sleves",
    },
    {
        pid:4,
        pname:"W Red Top",
        src:"http://localhost:3000/img/slider/pic4.jpg",
        ptitle:"Big Brand Textile",
        pcolor:"Light Red",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Cotton Mix",
        type:"Half Sleves",
    },
    {
        pid:5,
        pname:"Cream Jacket",
        src:"http://localhost:3000/img/slider/pic5.jpg",
        ptitle:"Big Brand Textile",
        pcolor:"Cream-Brown",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Cotton wool",
        type:"Full Sleves",
    },
    {
        pid:6,
        pname:"Combo Jacket",
        src:"http://localhost:3000/img/slider/pic6.jpg",
        ptitle:"Big Brand Textile",
        pcolor:"Black and Gray",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Synthetic",
        type:"Hybride",
    },
    {
        pid:7,
        pname:"3 pice Coat",
        src:"https://www.pexels.com/photo/young-elegant-man-standing-in-a-park-17373273/",
        ptitle:"Big Brand Textile",
        pcolor:"Black & White",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Fabric",
        type:"Full Sleves",
    },
    {
        pid:8,
        pname:"Balck Jacket",
        src:"http://localhost:3000/img/slider/pic8.jpg",
        ptitle:"Big Brand Textile",
        pcolor:"Royal Black",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Cotton Mix",
        type:"Full Sleves",
    },
    {
        pid:9,
        pname:"Cream Jacket",
        src:"http://localhost:3000/img/slider/pic9.jpg",
        ptitle:"Big Brand Textile",
        pcolor:"Cream-Brown",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Raxien",
        type:"Full Sleves",
    },
    {
        pid:10,
        pname:"Black hoddi",
        src:"http://localhost:3000/img/slider/pic10.jpg",
        ptitle:"Big Brand Textile",
        pcolor:"B-Black",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Cotton Mix",
        type:"Full Sleves",
    },
    {
        pid:11,
        pname:"Chinese Trade",
        src:"http://localhost:3000/img/slider/pic11.jpg",
        ptitle:"Big Brand Textile",
        pcolor:"Dark Black",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Polyseter Mix",
        type:"Full Sleves",
    },
    {
        pid:12,
        pname:"Cream Coat",
        src:"http://localhost:3000/img/slider/pic12.jpg",
        ptitle:"Big Brand Textile",
        pcolor:"Cream-Brown",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Cotton Mix",
        type:"FUll Sleves",
    },
    {
        pid:13,
        pname:"Multicolor Coat",
        src:"http://localhost:3000/img/slider/pic13.jpg",
        ptitle:"Big Brand Textile",
        pcolor:"Multi Color",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Cotton Mix",
        type:"Full Sleves",
    },
    {
        pid:14,
        pname:"Multicolor Coat",
        src:"http://localhost:3000/img/slider/pic14.jpg",
        ptitle:"Big Brand Textile",
        pcolor:"Multi Color",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Wedding Collection",
        type:"Full Sleves",
    },
    
    {
        pid:15,
        pname:"Blue Coat",
        src:"https://images.pexels.com/photos/17489878/pexels-photo-17489878/free-photo-of-young-elegant-man-in-a-suit-posing-outside-in-city.jpeg?auto=compress&cs=tinysrgb&w=600",
        ptitle:"Big Brand Textile",
        pcolor:"Gray Black",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Cotton Mix",
        type:"Full Sleves",
    },
]
module.exports=api;