const lowapi=[
    {
        pid:11,
        pname:"Chinese Trade",
        src:"http://localhost:3000/img/slider/pic11.jpg",
        ptitle:"Big Brand Textile",
        pcolor:"Dark Black",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Polyseter Mix",
        type:"Full Sleves",
    },
    {
        pid:12,
        pname:"Cream Coat",
        src:"http://localhost:3000/img/slider/pic12.jpg",
        ptitle:"Big Brand Textile",
        pcolor:"Cream-Brown",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Cotton Mix",
        type:"FUll Sleves",
    },
    {
        pid:13,
        pname:"Multicolor Coat",
        src:"http://localhost:3000/img/slider/pic13.jpg",
        ptitle:"Big Brand Textile",
        pcolor:"Multi Color",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Cotton Mix",
        type:"Full Sleves",
    },
    {
        pid:14,
        pname:"Multicolor Coat",
        src:"http://localhost:3000/img/slider/pic14.jpg",
        ptitle:"Big Brand Textile",
        pcolor:"Multi Color",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Wedding Collection",
        type:"Full Sleves",
    },
    
    {
        pid:15,
        pname:"Blue Coat",
        src:"https://images.pexels.com/photos/17489878/pexels-photo-17489878/free-photo-of-young-elegant-man-in-a-suit-posing-outside-in-city.jpeg?auto=compress&cs=tinysrgb&w=600",
        ptitle:"Big Brand Textile",
        pcolor:"Gray Black",
        discription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam soluta eos doloremque blanditiis dolores odit ullam odio doloribus perferendis at esse facere accusantium sed, ad, dignissimos nam ut error. Fuga corporis culpa illum quaerat. Soluta eum nam aut neque consequuntur incidunt amet dolor sit, officiis optio dignissimos labore esse exercitationem?",
        fiber:"Cotton Mix",
        type:"Full Sleves",
    },
];
module.exports=lowapi;